print('Feature1')
print('feature2')
print('Feature3')
print('feature4')
print('Local Features')
print('Local Features2')
print('Local Features3')
print('Local Features4')
print('Dilip')
print('My name is Dilip')
